### ISSUE TITLE
"no-unused-vars" rule shuld not be disabled

### ISSUE THREAD

**Issue by simevidas** [developit/preact-boilerplate#100]
I’ve noticed this rule in the ESLint config:

```js
"no-unused-vars": [0, { "varsIgnorePattern": "^h$" }]
```

The zero means that this rule is turned off, meaning unused variables will not be reported (at all).

I have just started writing a Preact web app, and I have found the following ESLint config to work well. It uses the `eslint-plugin-react` with its recommended rules. Unused variables are correctly reported, while components used in JSX as well the `h` pragma are recognized (so they’re not reported as unused variables).

```js
{
    "parser": "babel-eslint",
    "plugins": ["react"],
    "extends": ["eslint:recommended", "plugin:react/recommended"],
    "env": {
        "browser": true
    },
    "settings": {
        "react": {
            "pragma": "h"
        }
    }
}
```

It might be worth checking if `eslint-plugin-react` is compatible with Preact apps. I have just started writing my own app, so I can’t tell yet, but I can report back in a few weeks.

**Comment by developit** [comment]
I agree! Also yes, the react plugin is compatible with Preact out of the box.

**Comment by wardoost** [comment]
What about `"no-unused-vars": ["error", { "varsIgnorePattern": "^h$" }]` ?

**Comment by simevidas** [comment]
@wardoost IIRC, you would still get errors for (imported) components that are used in JSX.

Btw, since my last post, I’ve had to add these two rules to make the React preset compatible with my Preact code:

```js
"rules": {
    "react/prop-types": 0,
    "react/no-unknown-property": [2, { "ignore": ["class"] }]
}
```

**Comment by developit** [comment]
We should merge this - the ESLint config used here was one I had put together a very long time ago. Where I work we have been using `eslint-plugin-react` with Preact very much like your recommendation and it's been working well.

@simevidas mind adding those rules to the PR?  Also I wonder if we should just disable `react/no-unknown-property` - Preact does not maintain a whitelist, so it's acceptable to pass any property through to the DOM.

**Comment by simevidas** [comment]
@developit I used `<time datetime="...">` in JSX and `react/no-unknown-property` warned that I should use `dateTime` instead. IIUC, either is fine as far as Preact and browsers are concerned, but the camel notation makes the JSX code (more? fully?) compatible with React, so I guess it makes sense to prefer it. In that case, `no-unknown-property` would server a purpose in ensuring that camel notation is used where appropriate.

**Comment by developit** [comment]
JSX is increasingly unopinionated about attributes, as is React - for HTML attributes like the one on `<time>` it doesn't matter so much, but it might get annoying to have warnings for things like `xlink:href`, which is now valid JSX.  I'm not against having the rule, I just think it might be a little overzealous to enable it by default.

**Comment by simevidas** [comment]
In related news, when I want to destructure a state field, but don’t need props, like so:

```
class Foo extends Component {
  render({}, { bar }) {
    // use bar
  }
}
```

ES Lint’s `no-empty-pattern` error kicks in, so instead of `{}` I just used a dummy named variable:

```
class Foo extends Component {
  render(props, { bar }) {
    // use bar
  }
}
```

and ES Lint stopped complaining :) I guess, that’s the way to do it.

**Comment by developit** [comment]
@simevidas you have good timing - we actually just published the eslint configuration we use at Synacor. It looks like we run with `no-empty` turned off to avoid that warning:
https://github.com/synacor/eslint-config-synacor

**Comment by developit** [comment]
I ended up adding some React-ey rules to the config. I think we can close this issue now?

**Comment by simevidas** [comment]
This may be a dumb question, but how is the `.eslintrc` config used by this project? I’m unable to figure out where in the code it is loaded. 😅

**Comment by developit** [comment]
Ah - it's just there for `eslint`, so if your editor has an integration it'll show errors/warnings there. Also `npm test` is set up to run `eslint src test`.  There's no fancy redbox stuff going on.

**Comment by simevidas** [comment]
Ah, of course. 

Ok, now that eslint-plugin-react has been added, it’s possible to enable the `no-unused-vars` rule by doing what I’ve described in my original post above:

1. Remove

    ```js
    "no-unused-vars": [0, { "varsIgnorePattern": "^h$" }]
    ```

2. Add

    ```js
    "settings": {
        "react": {
            "pragma": "h"
        }
    }
    ```

I’ve tested this, and it works correctly (e.g. adding some random, unused parameter to a function will get reported). There already seems to be one unused variable in the project:

```
D:\projects\preact-boilerplate\test\components\profile\index.test.js
  3:10  error  'createClock' is defined but never used  no-unused-vars
```

**Comment by developit** [comment]
Awesome!
