### ISSUE TITLE
ERROR in bundle.js from UglifyJs

### ISSUE THREAD

**Issue by vitormalencar** [developit/preact-boilerplate#116]
I got this error when I try to run the build of my preact-boilerplate

`SyntaxError:`` Unexpected token: operator (>) [bundle.js:6613,70]

**Comment by developit** [comment]
@vitormalencar sorry - we're going to need a lot more information in order to figure out what's going on.  What versions of `node` and `npm` are you using? What browser?  What did you change before hitting the error?

**Comment by vitormalencar** [comment]
sorry about that =D , 

node: v6.9.5
npm : 3.10.10

The error was generated when I downloaded the repository, installed the dependencies and started the npm run build, I did not install any another dependency, 
I tried with other computers with similar configurations and versions of node and npm and get the same error.

**Comment by developit** [comment]
@vitormalencar I just tried and I can't reproduce the issue.

```sh
git clone git@github.com:developit/preact-boilerplate.git
cd preact-boilerplate
npm install
npm run build
npm start
```

Works and the built app works.  Are you using a custom npm registry or anything?

**Comment by developit** [comment]
I think this might have been due to a preact-compat release, but it's long fixed. Let me know if I'm wrong! :)

**Comment by vitormalencar** [comment]
I believe that was the case, @developit thanks again  =)
