### ISSUE TITLE
Why use both import and require?

### ISSUE THREAD

**Issue by silverlight513** [developit/preact-boilerplate#125]
In the file `/src/index.js` the first few lines are imports but then at line 8 a require is made with the addition of `.default`. That additional property being called means the file was exported using a native export. This import should instead be at the top using a native import.

**Comment by developit** [comment]
It's required for webpack HMR, since `import` is only allowed at the top level. Sadly `System.import()` won't work there either because of how webpack parses require() statements in the HMR callback. Cheers!

**Comment by developit** [comment]
To clarify: require() is the only way to do this because it's the only way to obtain the updated module definition from webpack.

**Comment by silverlight513** [comment]
You could have a simple express server with the webpack-dev-middleware and webpack-hot-middleware. That way you can use imports across the whole project.

Adding a simple express server means that server side rendering could be added with react-dom/preact-compat.

**Comment by developit** [comment]
That would not solve the issue. This is already using `webpack-dev-middleware` - that's what powers `webpack-dev-server`.  `webpack-hot-middleware` doesn't help here either - as stated in their readme, it's still up to the application to update in response to HMR.

Basically, something has to re-import the root module in order to re-render it.  Can't do that with ES Modules.

**Comment by silverlight513** [comment]
In my side project I'm using HMR with an express server in which I'm not using require at all. I'm not 100% sure how it works as I used a boilerplate and just tweaked it. I'll take a look at what I'm doing and see if I can come up with a viable solution. If I do find something, would it be okay to make a PR?

**Comment by developit** [comment]
Drop me a line first via [Twitter](https://twitter.com/_developit) or the [Preact slack](https://preact-slack.now.sh) if you find something - want to make sure first.
