### ISSUE TITLE
Small a11y improvement to consider.

### ISSUE THREAD

**Issue by robdodson** [developit/preact-boilerplate#192]
The meta viewport currently uses `maximum-scale=1.0, user-scalable=no` which is considered a bit of an anti-pattern for accessibility because it limits a user's ability to zoom the page. I believe mobile browsers ignore these directives, or they can be overridden via a user setting. But I'd suggest removing them entirely from the boilerplate so as not to encourage the pattern.

**Comment by developit** [comment]
Totally. We amended this in preact-cli since it's now monitored as part of lighthouse 2 👍

**Comment by robdodson** [comment]
Cool. It looks like you're setting a maximum scale of 5 over there
https://github.com/developit/preact-cli/blob/master/src/resources/template.html#L6

Any reason that number was chosen?

**Comment by developit** [comment]
Nope!
