### ISSUE TITLE
Stripping of new Error() breaks runtime sprintf-js

### ISSUE THREAD

**Issue by cmaster11** [developit/preact-boilerplate#197]
Using the [ReplacePlugin](https://github.com/developit/preact-boilerplate/blob/master/webpack.config.babel.js#L168) to strip out `throw new Error` looks not really efficient. 

When [sprintf-js](https://github.com/alexei/sprintf.js/blob/master/src/sprintf.js) library is used, together with UglifyJS, a [specific error](https://github.com/alexei/sprintf.js/blob/1.1.0/src/sprintf.js#L62) gets blown away by this setting.

**Comment by developit** [comment]
It's a little draconian, yeah. Ideally I would like to be able to replace only Babel errors. Perhaps a different regex can handle only those.
