### ISSUE TITLE
PostCSS not working

### ISSUE THREAD

**Issue by paulinhapenedo** [developit/preact-boilerplate#198]
Hello :)

The project I'm working on is using Flexbox, but it has to work on IE 10 and IE 11. `Display: flex;` should output `display: flex; display: -ms-flexbox`, but seems like PostCSS is not working because the outputed CSS has no autoprefixed value.

It's an out-of-the-box implementation. `Git clone && npm install`. Just changed the browsers lists to `['last 2 versions', 'Explorer > 8']` 

Thank you!

**Comment by developit** [comment]
Hi there!  I think this should be fixed now that we merged Autoprefixer 7. Are you able to test again?

**Comment by developit** [comment]
Closing since it appears to be fixed, please re-open if it's not.
