### ISSUE TITLE
Issue when importing styles

### ISSUE THREAD

**Issue by abacaj** [developit/preact-boilerplate#2]
Nice boilerplate - everything worked for me except...

The 3rd import in `components\header\index.js` `import style from './style';` returns an empty object - everything else builds fine with no errors in console I tried logging the import like so:

```
import style from './style';

function printStyle() {
    for (var i in style) {
        console.log(style[i]);
    }
    console.log(style);
}

printStyle();
```

and it is indeed empty... any ideas?

**Comment by developit** [comment]
If possible, could you post your stylesheet?
When you import, only classNames are imported as keys.

```css
.red {
  color: red;
}
.hidden {
  display: none;
}
```

```js
import style from './style';
console.log(style);
// { red:'red_1r23rt', hidden:'hidden_1r23rt' }
```

Also, I should note: CSS Modules (these local imports) is only enabled within the `src/components` directory.  You can change that if you want here:

https://github.com/developit/preact-boilerplate/blob/master/webpack.config.babel.js#L48

**Comment by abacaj** [comment]
The stylesheet is unmodified, I am running the base boilerplate with no modifications 

```
@import '~style/helpers';

.header {
	position: fixed;
	left: 0;
	top: 0;
	width: 100%;
	height: 56px;
	padding: 0;
	background: #673AB7;
	box-shadow: 0 0 5px rgba(0, 0, 0, 0.5);
	z-index: 50;

	h1 {
		float: left;
		margin: 0;
		padding: 0 15px;
		font-size: 24px;
		line-height: 56px;
		font-weight: 400;
		color: #FFF;
	}

	nav {
		float: right;
		font-size: 100%;

		a {
			display: inline-block;
			height: 56px;
			line-height: 56px;
			padding: 0 15px;
			min-width: 50px;
			text-align: center;
			background: rgba(255,255,255,0);
			text-decoration: none;
			color: #EEE;
			will-change: background-color;

			&:hover, &:active {
				background: rgba(255,255,255,0.3);
			}
		}
	}
}
```

**Comment by developit** [comment]
@abacaj hmm. I just did a fresh clone and install, and I'm seeing the imported styles object with a `.header` property when I log it.
Is it possible you somehow ended up with incorrect dependency versions?
Feel free to jump into the Preact chat (https://gitter.im/developit/preact) if you want quicker help!

**Comment by abacaj** [comment]
Ok I will try again per your suggestion and delete my folder and reclone.

**Comment by developit** [comment]
@abacaj Let me know if re-downloading fixed the issue so I can close :)

**Comment by developit** [comment]
@abacaj closing for now, please re-open if you're still having issues.
