### ISSUE TITLE
jest won't run

### ISSUE THREAD

**Issue by krokofant** [developit/preact-boilerplate#205]
```bash
git clone https://github.com/developit/preact-boilerplate
cd preact-boilerplate
yarn
npm run test
```
And it seems it does nothing 😕 

Linting errors does work but the jest part does not seem to work.

env
zsh
macOS Sierra 10.12.3
node v8.1.2
npm 5.0.3
preact-boilerplate 6.0.0/master

Anyone with a similar environment where it runs okay? I'm not sure how to proceed debugging this. I want tests 😁

**Comment by developit** [comment]
This is a Node 8 / npm 5 bug - there are quite a few, I would recommend using a different version for now.

**Comment by krokofant** [comment]
node v6.11.0
npm 3.10.10

```bash
git clone https://github.com/developit/preact-boilerplate
cd preact-boilerplate
yarn
npm run test
```
same result
