### ISSUE TITLE
Don't optimize code twice

### ISSUE THREAD

**Issue by krokofant** [developit/preact-boilerplate#208]
The build script is specified as the following:
```
cross-env NODE_ENV=production webpack -p --progress
```

Which to my understanding, based on the link below, applies optimizations twice.

Which in turn produces the following error:
```
ERROR in bundle.js from UglifyJs
TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/Users/krokofant/GitHub/preact-todo/node_modules/source-map/lib/source-map-consumer.js:20:19)
    at /Users/krokofant/GitHub/preact-todo/node_modules/uglifyjs-webpack-plugin/dist/index.js:75:21

```

Solution
Reference https://github.com/webpack/webpack/issues/1385#issuecomment-160553651

>when using new UglifyJsPlugin and --opimize-minimize (or -p) you are adding the UglifyJsPlugin twice. Omit the CLI option.
> -sokra

Perhaps the build script should be changed then to omit the `-p` option?

**Comment by developit** [comment]
Yup. Fixed in #209 :)
