### ISSUE TITLE
await needed in router tests (app.test.js)?

### ISSUE THREAD

**Issue by raphaelbauer** [developit/preact-boilerplate#237]
Hi,

not really an issue - more like a question. 

Is it really needed to await and sleep in the app.test.js?
https://github.com/developit/preact-boilerplate/blob/3fa20ef53c2cd30536f555561b908a001f94d660/test/components/app.test.js#L36

Thanks!

**Comment by developit** [comment]
Yes, it's waiting for state updates to be flushed to the DOM.

**Comment by raphaelbauer** [comment]
Cool. Thanks! 
And I suppose there is no other "clean" way to wait for the update... right? Like waiting for a callback... or some signal like "updated rendering"....

**Comment by developit** [comment]
A setState() would provide that callback, or you can turn off async rendering entirely:

```js
import { options } from 'preact';
options.debounceRendering = f => f();
```

**Comment by raphaelbauer** [comment]
Cool. Thanks!
