### ISSUE TITLE
code coverage

### ISSUE THREAD

**Issue by zaccolley** [developit/preact-boilerplate#24]
what's the best way of adding some code coverage to this? finding it hard to implement, was trying to use karma-coverage but cant get webpack to play nicely with it.

**Comment by developit** [comment]
@zaccolley I haven't had to set that up yet with this test harness - I generally just track overall code quality with tools like Plato.

Looking around I feel like this is the closest thing to sanity that is currently available:
https://github.com/webpack/karma-webpack/issues/21#issuecomment-108957186

Ideally, the coverage should be reported against the ES6 source and tests, it feels wrong to run it against transpiled code.

**Comment by developit** [comment]
Added!
