### ISSUE TITLE
Example of SW integration

### ISSUE THREAD

**Issue by kontrollanten** [developit/preact-boilerplate#272]
It would be great if we could add some example on how to integrate the Service Worker with the preact app. I guess the common scenario when an update is available is to show a message for the user, for example. I'm not sure what the best way to handle that is, though. One idea is to create a middleware that listens for SW events. Any other ideas?

**Comment by developit** [comment]
We do show an example, just instead of prompting, it immediately reloads:
https://github.com/developit/preact-boilerplate/blob/master/src/pwa.js#L10-L14

**Comment by kontrollanten** [comment]
Yes, but in my humble opinion that's not a great user experience and that's why I think it would help a lot developers if there was a provided example where the user was prompted. But since there's no global state handler in the boilerplate that may be hard to do. Maybe it would be possible to just post a message to the client and do the `console.log` there. Just to show the communication between SW and the client

**Comment by developit** [comment]
Ah - so that file actually isn't running in the ServiceWorker scope. It's running on the main thread, where it could just invoke preact rendering or whatever when there's an SW update. The update already passes a message to the main thread and calls the methods defined in that file.
