### ISSUE TITLE
Static HTML files? question

### ISSUE THREAD

**Issue by iivn** [developit/preact-boilerplate#276]
Hi there,

I want to generate static HTML files without the bundle.js-script inside? PurifyCSS (or something similar) helps me to put the CSS to the head. But how can I avoid the bundle.js? Unfortunately I can't find something on the web. Maybe I have the wrong buzzwords. Any ideas what I should look up?

I'm working on AMP. So there are no external scripts allowed.

Thx,
I.

**Comment by developit** [comment]
Hi there,

Preact is a client-side rendering library - aside from using `preact-render-to-string` to do Server-Side rendering, it's likely not what you're looking for.
