### ISSUE TITLE
requestAnimationFrame for HMR ?

### ISSUE THREAD

**Issue by ptbrowne** [developit/preact-boilerplate#293]
Why is the `requestAnimationFrame` necessary here ?

https://github.com/developit/preact-boilerplate/blob/master/src/index.js#L20

```
	module.hot.accept('./components/app', () => requestAnimationFrame(init) );
```

I imagine it is there to ensure that the render with the new code happen after all "in-flight" renders (with ancient code) but I'm not sure...

**Comment by developit** [comment]
It's actually in there so that HMR'd CSS has a chance to be inserted prior to the components that depend on it being re-rendered. It's possible this is unnecessary in Webpack 3+, not sure.

**Comment by ptbrowne** [comment]
Thanks :)
