### ISSUE TITLE
error webpack

### ISSUE THREAD

**Issue by iano123** [developit/preact-boilerplate#3]
Hi

thank you for making this starter kit.
I have a problem: whenever I try to pack the project or run the project I get the following error. It seems like it does not understand the import statements

import webpack from 'webpack';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at loader (/usr/local/lib/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at module.exports (/usr/local/lib/node_modules/webpack/bin/convert-argv.js:93:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack/bin/webpack.js:114:40)

**Comment by developit** [comment]
Hi @iano123: that appears to be a webpack version issue. How are you running the build?

Please post the output of `npm ls --depth 0`.

Cheers!

**Comment by iano123** [comment]
jans-MacBook:preact jan$ npm ls --depth 0
preact-boilerplate@1.0.2 /Users/jan/Documents/proj/preact
├── autoprefixer@6.3.1
├── babel@6.3.26
├── babel-core@6.4.5
├── babel-eslint@5.0.0-beta8
├── babel-loader@6.2.1
├── babel-plugin-transform-decorators-legacy@1.3.4
├── babel-plugin-transform-react-jsx@6.4.0
├── babel-preset-es2015@6.3.13
├── babel-preset-es2015-minimal@1.1.0
├── babel-preset-stage-0@6.3.13
├── babel-register@6.4.3
├── babel-runtime@6.3.19
├── chai@3.5.0
├── core-js@2.0.3
├── css-loader@0.23.1
├── decko@1.1.3
├── eslint@1.10.3
├── extract-text-webpack-plugin@1.0.1
├── file-loader@0.8.5
├── html-webpack-plugin@1.7.0
├── json-loader@0.5.4
├── less@2.6.0
├── less-loader@2.2.2
├── ncp@2.0.0
├── npm-run-all@1.5.1
├── postcss-loader@0.8.0
├── preact@2.8.2
├── preact-compat@0.5.0
├── preact-router@1.1.0
├── proptypes@0.14.1
├── raw-loader@0.5.1
├── source-map-loader@0.1.5
├── superstatic@4.0.1
├── url-loader@0.5.7
├── webpack@1.12.12
├── webpack-config-babel@0.2.0
└── webpack-dev-server@1.14.1

**Comment by iano123** [comment]
Dunno if it matters, prob not but I am running this on a Mac

node --version
v5.4.1
jans-MacBook:preact jan$ npm --version
3.3.12

**Comment by developit** [comment]
Ah yes this will be due to npm 3. Will look into it!

**Comment by developit** [comment]
@iano123 I just did the full clone and install using your node and npm versions and it works.
That said, looking at the first output you posted, you're using a global installation of `webpack` that happens to be too old to recognize ES6 configurations.

There are two solutions:

Option 1: Just use `npm run build` and `PORT=8080 npm run dev` to trigger builds and live-reload, respectively. This keeps webpack versions local to each project, which is better for encapsulation.

Option 2: If you want to keep using `webpack` globally, update to the latest version by running `npm i -g webpack webpack-dev-server`.

**Comment by iano123** [comment]
Iĺl update the global one. Iĺl let you know if this solves the issue as soon as I get home

**Comment by developit** [comment]
@iano123 awesome, thanks for investigating :)

**Comment by iano123** [comment]
No sir, thank you for your work.

**Comment by developit** [comment]
@iano123 Closing for now but please let me know if this was not resolved by updating your global webpack version.
