### ISSUE TITLE
unexpected token {

### ISSUE THREAD

**Issue by pradeep0508** [developit/preact-boilerplate#323]
I'm using jest for testing cases but I facing below issue when I'm running test cases. 

Test suite failed to run

    **/**/Dropdown/index.jsx:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { h, Component } from 'preact';
                                                                                                    ^

    SyntaxError: Unexpected token {

      at new Script (vm.js:85:7)
      at Object.<anonymous> (**/components/filter-sort/index.jsx:2:43)

**Comment by developit** [comment]
Please use preact-cli.
