### ISSUE TITLE
How about a preact-cli or something like this?

### ISSUE THREAD

**Issue by Obooman** [developit/preact-boilerplate#44]
It's necessary for these react-like libraries to serve a tool to generate initial develop environment,Which we can be used to `preact-cli init Myproject` to set up the project or `preact-cli release` to release the project instead of `git clone - rm -surge` way.

**Comment by developit** [comment]
What about this?
https://github.com/alexkuz/create-preact-app

**Comment by Obooman** [comment]
Not bad,add this repo to README please and I'll test this.
