### ISSUE TITLE
How to use with Express?

### ISSUE THREAD

**Issue by daslicht** [developit/preact-boilerplate#5]
Hi,
how would we use this with Express instead of superstatic or the webpack-server, please?

**Comment by developit** [comment]
For express, you should pre-build the app:

### 1. Generate the static app build files:

```sh
npm run build
```

### 2. Serve them with express:

```
import express from 'express';
let app = express();
app.use(express.static('./build'));
app.listen(process.env.PORT);
```

**Comment by daslicht** [comment]
Thank you!
