### ISSUE TITLE
Example render broken when route?

### ISSUE THREAD

**Issue by katopz** [developit/preact-boilerplate#57]
When I navigate by click the link e.g. `Me`, `John` . It seem like page render not correctly it only show partial content below.
```
Preact Boilerplate

HomeMeJohn
```
Only home is fine at first render, btw with `preact@beta` seem to be working perfectly (except missing style), 5.x look broken to me.
FYI : I test this on Windows

**Comment by katopz** [comment]
On mac when I click profile, it'll not render content (on windows, style is missing and appear like `<header class>`  for some reason, I'll try again tmr in case mac is fine)

![screen shot 2016-08-30 at 23 29 47](https://cloud.githubusercontent.com/assets/97060/18097828/bdcc0236-6f09-11e6-9db5-9d739bfab8b5.png)

I've to hit refresh to force it render content.

And on my mac `preact@beta` working perfectly.

**Comment by developit** [comment]
Hey @katopz you're right, this needs preact 6! Will update shortly

**Comment by katopz** [comment]
@developit  So test suppose to fail? And also [![Build Status](https://travis-ci.org/developit/preact-boilerplate.svg?branch=master)](https://travis-ci.org/developit/preact-boilerplate) shouldn't pass? :)

**Comment by developit** [comment]
i think they are failing, just that travis badge points to Master which hasn't been updated so there was never a new build (dep update only):
https://travis-ci.org/developit/preact-boilerplate/builds

**Comment by katopz** [comment]
Something wrong with Windows. I did wipe out and try all over again but still has empty class issue.
Not sure this only me.

![preact-style-missing](https://cloud.githubusercontent.com/assets/97060/18125770/1a5d7398-6fa2-11e6-9e3e-a85af9fcf33c.png)

Here's what it look like ATM.

**Comment by developit** [comment]
@katopz- even after running `npm i -S preact@6`?

**Comment by katopz** [comment]
I'll try that TMR, at home on my Mac now ;)

**Comment by sambeau** [comment]
@developit Can confirm. `npm i -S preact@6` works for me.

**Comment by developit** [comment]
Fixed and published as [5.0.0](https://github.com/developit/preact-boilerplate/releases/tag/5.0.0)
