### ISSUE TITLE
Unused dependency

### ISSUE THREAD

**Issue by katopz** [developit/preact-boilerplate#58]
I think many dependency is never use but still include? e.g. decko, wildemitter and maybe something else that I'm not sure it use somewhere or not, so it should be nicer to clean it up?

**Comment by developit** [comment]
Wildemitter is still used for the pubsub example, but I think it needs to be removed.  We should be nice and clean these out as part of updating it to Preact 6 💃

**Comment by developit** [comment]
Fixed and published as [5.0.0](https://github.com/developit/preact-boilerplate/releases/tag/5.0.0)
