### ISSUE TITLE
superstatic route rewrite needs to be updated

### ISSUE THREAD

**Issue by billneff79** [developit/preact-boilerplate#6]
In the "start" npm command, it is starting superstatic with a rewrite of all paths to index.html, but the configuration of that route is not working with superstatic@4.0.1.  Current setup:
````
"start": "superstatic build -p ${PORT:-8080} --host 0.0.0.0 --gzip -c '{\"routes\":{\"**\":\"index.html\"},\"cache_control\":{\"**\":86400}}'",
````

I fixed it in my local instance by setting the setting to:

````
  "start": "superstatic build -p ${PORT:-8080} --host 0.0.0.0 --gzip -c '{\"rewrites\": [{\"source\":\"**\",\"destination\":\"index.html\"}],\"cache_control\":{\"**\":86400}}'",
````

**Comment by billneff79** [comment]
Created Pull Request #7 for this.

**Comment by developit** [comment]
Released along with the `superstatic@4` update in [2.0.0](https://github.com/developit/preact-boilerplate/releases/tag/2.0.0).
