### ISSUE TITLE
Class is empty when build via Windows

### ISSUE THREAD

**Issue by katopz** [developit/preact-boilerplate#62]
Here's different
On mac (working fine `<header class="header_3fP58">`)
![screen shot 2016-09-01 at 22 27 33](https://cloud.githubusercontent.com/assets/97060/18173452/cfe76164-7093-11e6-88b2-050c62f1df9c.png)

``` js
t["default"]=s},function(e,t){},function(e,t){e.exports={header:"header_3fP58"}},function(e,t){e.exports={home:"home_2xyY2"}},function(e,t){e.exports={profile:"profile_JmD9R"}}]);
//# sourceMappingURL=bundle.js.map
```

On Windows (appear `<header class>`)
![screen shot 2016-09-01 at 22 27 42](https://cloud.githubusercontent.com/assets/97060/18173458/d7fefb96-7093-11e6-8601-02bdd65cfa7b.png)

``` js
t["default"]=s},function(e,t){},7,7,7]));
//# sourceMappingURL=bundle.js.map
```

As you can see some export is missing on Windows build, Any idea? Maybe some build script is working only on Mac?

**Comment by katopz** [comment]
Not sure it related to this line https://github.com/developit/preact-boilerplate/blob/master/webpack.config.babel.js#L54

Maybe `${process.env.CSS_MODULES_IDENT...` is not process via WIndows What to expect for it value btw? also `${CSS_MAPS}` should be broken to I think.

**Comment by developit** [comment]
Ah yeah that seems like the issue. I don't have a Windows machine to test on!

**Comment by katopz** [comment]
This should do it
```
			{
				test: /\.(less|css)$/,
				include: /src\/components\//,
				loader: ExtractTextPlugin.extract('style?singleton', [
					'css?sourceMap=' + CSS_MAPS + '&modules&importLoaders=1&localIdentName=[local]' + (process.env.CSS_MODULES_IDENT || '_[hash:base64:5]') + '}',
					'postcss',
					'less?sourceMap=' + CSS_MAPS
				].join('!'))
			},
			{
				test: /\.(less|css)$/,
				exclude: /src\/components\//,
				loader: ExtractTextPlugin.extract('style?singleton', [
					'css?sourceMap=' + CSS_MAPS,
					'postcss',
					'less?sourceMap=' + CSS_MAPS
				].join('!'))
			},
```
Working fine on my Mac ATM, I'll test tmr and let you know. :)

**Comment by katopz** [comment]
Ah something completely wrong even fixed value didn't seem to made it
```
			{
				test: /\.(less|css)$/,
				include: /src\/components\//,
				loader: ExtractTextPlugin.extract('style?singleton', [
					'css?sourceMap=true&modules&importLoaders=1&localIdentName=[local]_[hash:base64:5]}',
					'postcss',
					'less?sourceMap=true'
				].join('!'))
			},
			{
				test: /\.(less|css)$/,
				exclude: /src\/components\//,
				loader: ExtractTextPlugin.extract('style?singleton', [
					'css?sourceMap=true',
					'postcss',
					'less?sourceMap=true'
				].join('!'))
			},
```

I think I need other Windows to confirm this.

**Comment by developit** [comment]
Might be the include/exclude regular expressions.

**Comment by wuvluv** [comment]
Can confirm this is happening on my Windows 7 system.

After snooping around this seems to be a core issue with css-loader.
https://github.com/webpack/css-loader/issues/180

It may be due to how paths are read on windows systems by css-loader.

**Comment by bang88** [comment]
@developit any updates ?

**Comment by katopz** [comment]
@developit didn't have Windows to test tho, we should help him out. 
Let's start with trying to find working one first. 

I think many React boilerplate did have nearly same webpack config and it did working.
Can you guys help finding closet working one (but in React) so we can start to scope the problems down?

Cheers

**Comment by developit** [comment]
Thanks guys, you're right this is something pretty difficult for me to test. I had a thought though: what about removing the `localIdentName` parameter entirely? The default is pretty close to the value it is being manually set to, and that might be safer.

**Comment by wuvluv** [comment]
@developit 
```
{
				test: /\.(less|css)$/,
				include: /src\/components\//,
				loader: ExtractTextPlugin.extract('style?singleton', [
					`css?sourceMap=${CSS_MAPS}&modules&importLoaders=1`,
					'postcss',
					`less?sourceMap=${CSS_MAPS}`
				].join('!'))
			},
			{
				test: /\.(less|css)$/,
				exclude: /src\/components\//,
				loader: ExtractTextPlugin.extract('style?singleton', [
					`css?sourceMap=${CSS_MAPS}`,
					`postcss`,
					`less?sourceMap=${CSS_MAPS}`
				].join('!'))
			},
```

Same result with these settings. Let me know any other settings you may want to try.

@katopz One I have personally seen to generate the css-modules classes correctly is: https://github.com/MoOx/phenomic

Although it uses react, as you specified. Unfortunately i'm very green to webpack but I am willing to test anything you guys might think could fix the issue at hand.

Here's the excerpt from Phenomics webpack.config for .css -> css modules. Excuse my tabbing (or lack there-of, just pasted from notepad++)


```
        {
          test: /\.css$/,
          exclude: /\.global\.css$/,
          include: path.resolve(__dirname, "src"),
          // webpack 1
          loader: ExtractTextPlugin.extract(
            "style-loader",
            [ `css-loader?modules&localIdentName=${
              config.production
              ? "[hash:base64:5]"
              : "[path][name]--[local]--[hash:base64:5]"
              }`,
              "postcss-loader",
            ].join("!"),
          ),
```

Thanks for your work on this guys, I appreciate it greatly.

**Comment by bang88** [comment]
@katopz  @wuvluv See #82 ,It should works on both Windows and Mac,if it doesn't please let me know.Thank you.

**Comment by wuvluv** [comment]
@bang88 This fixes the issue on my Windows 7 system. Thank you!

**Comment by bang88** [comment]
@wuvluv You are welcome. :)

**Comment by developit** [comment]
I'll see about checking this on mac today.  I think it might actually have been the regex matching against `src/components` that broke it!
