### ISSUE TITLE
HMR - Home not trigger render?

### ISSUE THREAD

**Issue by katopz** [developit/preact-boilerplate#64]
Other page is fine but HMR at Home page didn't render after modified code. and I need to add `componentDidMount` to made it work for some reason.
```js
import { h, Component } from 'preact';
import style from './style';

export default class Home extends Component {
	// Not sure why I need this to make HMR work?
	componentDidMount() {
		this.setState(this.state);
	}

	render() {
		return (
			<div class={style.home}>
				<h1></h1>
				<p>This is the Home component.</p>
			</div>
		);
	}
}
```
I'm not sure I doing it right btw. any advice is welcome. Thanks.

**Comment by developit** [comment]
@katopz Thanks so much for pointing this out - turns out it was actually a bug in 6.0!  I've migrated the issue there, so I'll close this one out.
