### ISSUE TITLE
ReferenceError: dom is not defined 

### ISSUE THREAD

**Issue by linuxenko** [developit/preact-boilerplate#79]
Strange thing happen with application when i open it in web browser:

[![fail](http://i.imgur.com/8pFaHB9.png)](http://i.imgur.com/8pFaHB9.png)

started with `npm run start`

**Comment by developit** [comment]
Hmm. Never seen that before. What about `npm run dev`?

**Comment by developit** [comment]
I'm going to close this since it looks like this is a server configuration issue, not related to this repo. Let me know if you have more info!
