### ISSUE TITLE
Why it uses preact-compat?

### ISSUE THREAD

**Issue by budarin** [developit/preact-boilerplate#95]
this project is for demonstrate the power of preact itself not react compatibility!
Is there a way create pure preact-boilerplate, without react components?

**Comment by developit** [comment]
It only _enables_ preact-compat, nothing is actually using it. This is intentionally done so that if you install a react component as a dependency, it just works. If you look at the build output, preact-compat is not included. It only gets added if something does `import 'react'`.

**Comment by budarin** [comment]
Thanks!
may be should it mention in doc?

**Comment by developit** [comment]
Sounds like a good idea!

**Comment by budarin** [comment]
I'm sorry if I bore you with a bunch of questions.
We just released a big project in React.
So I see huge advantages in rendering speed in preact and really want to use preact in new project.

**Comment by developit** [comment]
No problem at all! You might find it easier and faster to chat via Gitter though. There are a bunch of people happy to answer questions at [gitter.im/developit/preact](https://gitter.im/developit/preact) 😊
