### ISSUE TITLE
have a problem with hotreload on linter errors

### ISSUE THREAD

**Issue by jt3k** [developit/preact-boilerplate#96]
![preact-hot-404](https://cloud.githubusercontent.com/assets/1261240/21342498/468d05ac-c6a3-11e6-9c2a-98192cb79ce8.gif)
how to prevent hiding the linters_red_error_screen ?

**Comment by developit** [comment]
@jt3k Use `http://localhost:8080` instead of `http://localhost:8080/webpack-dev-server/`.  Let me know if that fixes the issue!

**Comment by jt3k** [comment]
Yep. is fix the problem.  But...

In this case, an error message is displayed in the developer console, not inside the viewer.

Is there a way to display the error message inside the viewport?, as it happens in [preact-todomvc](https://github.com/developit/preact-todomvc)

**Comment by developit** [comment]
I usually keep my terminal open to see the errors, since they are syntax-highlighted there.
There's also "redbox" plugins for webpack you can find around.
