### ISSUE TITLE
Probably Invalid Dependency in package.json

### ISSUE THREAD

**Issue by abhishekisnot** [developit/preact-boilerplate#97]
On installing packages for boilerplate using yarn I see below warning.

warning preact-boilerplate@5.0.0: Dependency "path" listed in "devDependencies" is the name of a built-in module

which leads me to believe the path is maybe incorrect dependency.

Probably related to https://github.com/jinder/path/issues/6

**Comment by developit** [comment]
We can remove `path` yeah, it slipped in from a PR a while ago.
