### ISSUE TITLE
Does not build with node version <6 

### ISSUE THREAD

**Issue by TheNeikos** [developit/preact-boilerplate#99]
It fails with:
```
error args@2.2.1: The engine "node" is incompatible with this module. Expected version ">= 6.0.0".
```

Fixed it by raising the node version to at least 6 (from the current 4)

**Comment by developit** [comment]
I changed the CI node version to 6 - didn't realize `args` had started requiring Node 6+, I guess that's inevitable.  Perhaps this means we should just move to 6? That'd mean we could merge #93 since it was waiting on upstream Node 4 support.

**Comment by TheNeikos** [comment]
I have to admit, I don't know. I just started out with JS Dev after a hiatus of 3 years and decided to check out preact :smile: and this is the error I got when running it on travis (and decided to report it back)

**Comment by developit** [comment]
All good! I hadn't noticed this yet so thanks a bunch :)
If you want any tips or anything, we just set up a Slack for Preact:
https://preact-slack.now.sh

**Comment by TheNeikos** [comment]
Thanks, gonna check it out
